.github/workflows/job_detect_cp_resource_wastage.yml
Pipfile
Pipfile.lock
bin/detect_cp_resource_wastage.py
services/github_service.py
services/slack_service.py

- Added logic to send slack notification and workflow to run the automation
- Added workflow file to trigger job on dispatch
- Integration with slack to send the notification to operations-engineering channel
- [#5278](https://github.com/ministryofjustice/operations-engineering/issues/5278) 
---

logic to send alert to slack and worflow added

---

services/slack_service.py

- Added count of wasted resources to the notification message
- updated slack_service
- NA
---

added count for resources to the message

---

dashboards/COAT 🧥-grafana.json
dashboards/GPX PoC-1742480931514.json

Copying the dashboards to our repo in case the observability platform Grafana goes down or someone modifies them by mistake

Grafana dashboards for FinOps and GreenOps

---

.github/workflows/job-find-ebs-volume-owners.yml
bin/find_ebs_volume_owners.py
services/slack_service.py

-  Added workflow for automatic run of the script and logic to send report to the slack channel 
- Added workflow definition 
- Added Slack service 
- NA
---

added workflow and slack service integration

---

Pipfile
Pipfile.lock

- Added pandas to pipenv
- 
-[#5306](https://github.com/ministryofjustice/operations-engineering/issues/5306) 
---

added pandas to pipenv

---

.github/workflows/cicd-trivy-dependency-scan.yml

- Added Trivy Vulnerability Scan workflow to the repo
- 
- NA
---

added trivy security scan workflow

---

bin/find_ebs_volume_owners.py

-  [#5360](https://github.com/ministryofjustice/operations-engineering/issues/5360)

fixed intendation

---

.github/workflows/job-find-ebs-volume-owners.yml
.github/workflows/job_detect_cp_resource_wastage.yml

-  [#5360](https://github.com/ministryofjustice/operations-engineering/issues/5360)

updated schedule to once per month

---

source/CNAME

Adds a CNAME file to use the custom domain created for the document site cloud-optimisation-and-accountability.justice.gov.uk

Adds CNAME file

---

bin/find_ebs_volume_owners.py
test/test_bin/test_find_ebs_volume_owners.py

- Added Aggregated cost and saving report generation
- Modified bin/find_ebs_volume_owners
- [#5399 ](https://github.com/ministryofjustice/operations-engineering/issues/5399)
---

Added aggregated report generation

---

.github/ISSUE_TEMPLATE/ticket-template.md

- To create the standard ticket template agreed in our [team session](https://miro.com/app/board/uXjVMYOTvek=/?moveToWidget=3458764634008894465&cot=14)
- ✨ Adds Stnadrd Ticket Template
- I've put every section as either a bullet point list or a checklist, but we can refined how these look later if that's not ideal ♻️

✨ Add Standard Ticket Template

---

.github/ISSUE_TEMPLATE/ticket-template.md

- Fixes #164 
- Adds Missing `about` Attribute

🔧 Fix Issue Template Missing `about` Attribute

---

source/documentation/finops-and-greenops-at-moj/finops-and-greenops-at-moj.html.md.erb
source/documentation/finops-and-greenops-at-moj/patterns/reserved-instances.html.md.erb

• This PR adds guidance around use of reserved instances for users.
• Add "Reserving Infrastructure Capacity" guide
• Update index page

Add Reserved Instance guide

---

source/documentation/team-information/team-practises/ways-of-working.html.md.erb

• This PR removes reference to stakeholders in our Demo sessions.
• Update Demo description.
From [WoW Review](https://miro.com/app/board/uXjVMYOTvek=/?share_link_id=531799601845)

Update Demo details

---

source/documentation/team-information/internal-processes/communication-plan.html.md.erb

• This PR updates our communication plan to reflect new Team mission. Remove unnecessary communications tasks and content.
• Updates to Communication Plan

Update communication plan

---

source/documentation/team-information/team-practises/ways-of-working.html.md.erb

To add delivery updates from our WoW review meetings
•
- Add a comment that we will add links any relevant PR's stories to the comments section of our tickets
- Changed 'Sprint backlog contents' to 'Current sprint contents'
- Add WoW reflection retro to Quarterly Goals
•

Add WoW review updates

---

source/documentation/team-information/internal-processes/assess-reserved-instances.html.md.erb

Add missing file type

---

terraform/github/repositories/orgs.tf

•     Manage COAT GitHub Team and Repos via IAC. https://github.com/ministryofjustice/cloud-optimisation-and-accountability/issues/191
•.  Added terraform > github subfolders inside cloud-optimisation-and-accountability repo main folder and added the following repos in ministryofjustice folder to enable repo access and creation
cloud-optimisation-and-accountability
coat-cur-data-pipeline
Testing in progress commented

commented module

---

terraform/github/repositories/orgs.tf

• Manage COAT GitHub Team and Repos via IAC. https://github.com/ministryofjustice/cloud-optimisation-and-accountability/issues/191
• Added terraform > github subfolders inside cloud-optimisation-and-accountability repo main folder and added the following repos in ministryofjustice folder to enable repo access and creation
cloud-optimisation-and-accountability
coat-cur-data-pipeline

guthub modules

---

source/documentation/operations-engineering-legacy/operations-engineering-user-guide/ci/circleci.html.md.erb

• Fixes broken image links
• Update image file path

Fix broken image links

---

source/documentation/team-information/team-practises/ways-of-engineering.html.md.erb

• Formalise when to use AP
• ✨ Add a section about using AP for data pipelines

Add a section about using AP for data pipelines

---

source/documentation/team-information/team-practises/ways-of-engineering.html.md.erb

• Add details for Terraform as IAC
• Added Info for Terraform

woe document update A023

---

source/documentation/team-information/team-practises/ways-of-engineering.html.md.erb

• Action items for WoE A023 and A026
• Site updated with details for WoE A023 and A026 action items

Woe document update

---

dashboards/COAT 🧥-grafana.json

• Updates for Dashboard:
- Filter Business unit displays cost_category('business_unit')
- Corrected Tagging Coverage Calculations
- Corrected Costs formulas to apply BU based on cost_categories
- Corrected Cost Formulas per BU to display Net Unblended Cost after all discounts are applied. 
• Row SQL queries updated
[#5483 ](https://github.com/ministryofjustice/operations-engineering/issues/5483)

Dashboard Updates

---

dashboards/COAT 🧥-grafana.json

• Updated cost queries in 'Cost in USD' and 'Regions'
• Updated Raw SQL queries in JSON model
[#5487](https://github.com/ministryofjustice/operations-engineering/issues/5487)

updated cost queries in 'Cost in USD' and 'Regions'

---

source/documentation/team-information/team-practises/ways-of-engineering.html.md.erb

• Update ways of Engineering document from retro actions
• Add details of the teams Hackathon to the Security and Dependency section of the WoE document

Add hackathon to WoE document
